apiVersion: v1
kind: Service
metadata:
  name: mysql-service-k8s
spec:
  selector:
    app: mysql-deployment-k8s
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306
  type: NodePort